# Generated by Django 2.2.8 on 2020-05-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_commentaire_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Article'),
            preserve_default=False,
        ),
    ]
