# Generated by Django 2.2.8 on 2020-05-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentaire_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
    ]
