# Generated by Django 3.0.6 on 2020-05-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commentaire_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
