# Generated by Django 3.0.6 on 2020-05-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='date_update',
            new_name='date_upd',
        ),
    ]
