# Generated by Django 2.2.8 on 2020-05-13 16:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200512_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='contenu',
            field=tinymce.models.HTMLField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
