# Generated by Django 3.0.6 on 2020-05-27 18:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produit_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Content/description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='information',
            field=tinymce.models.HTMLField(default='', verbose_name='Content/information'),
            preserve_default=False,
        ),
    ]
