# Generated by Django 3.0.6 on 2020-05-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
