# Generated by Django 3.0.6 on 2020-05-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('isValide', models.BooleanField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='CommandeContenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixUnitaire', models.IntegerField(default=0)),
                ('quantité', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenu', to='shop.Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_contenu', to='shop.Produit')),
            ],
            options={
                'verbose_name': 'CommandeContenu',
                'verbose_name_plural': 'CommandeContenus',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(related_name='commandes', through='shop.CommandeContenu', to='shop.Produit'),
        ),
    ]
