# Generated by Django 3.0.6 on 2020-05-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200512_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='isrecommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='prix',
            field=models.FloatField(),
        ),
    ]
