# Generated by Django 2.2.8 on 2020-05-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200512_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurant.Categorie'),
            preserve_default=False,
        ),
    ]
