# Generated by Django 2.2.8 on 2020-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200529_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.CharField(max_length=255, unique=True)),
                ('hdebut', models.TimeField(blank=True, null=True)),
                ('hfin', models.TimeField(blank=True, null=True)),
                ('tel', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phydata',
                'verbose_name_plural': 'Phydatas',
            },
        ),
    ]
