# Generated by Django 2.2.8 on 2020-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_phydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True)),
                ('tel', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tel',
                'verbose_name_plural': 'Tels',
            },
        ),
        migrations.RemoveField(
            model_name='phydata',
            name='tel',
        ),
    ]
