# Generated by Django 3.0.6 on 2020-05-30 09:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20200529_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, unique=True)),
                ('ticket', models.IntegerField()),
                ('tick_rest', models.IntegerField()),
                ('prix', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='', verbose_name='events/images')),
                ('titre_slug', models.SlugField(editable=False, max_length=255, null=True)),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', tinymce.models.HTMLField(verbose_name='events/description')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('ticket', models.ManyToManyField(related_name='Events', to='restaurant.Ticket')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
