# Generated by Django 3.0.6 on 2020-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20200530_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='heure',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(max_length=50),
        ),
    ]
