# Generated by Django 3.0.6 on 2020-05-30 18:03

from django.db import migrations, models
import restaurant.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20200530_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, unique=True)),
                ('ticket', models.IntegerField()),
                ('tick_rest', models.IntegerField()),
                ('prix', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AlterField(
            model_name='phydata',
            name='jours',
            field=restaurant.models.DayOfTheWeekField(choices=[('1', 'lundi'), ('2', 'mardi'), ('3', 'mercredi'), ('4', 'jeudi'), ('5', 'vendredi'), ('6', 'samedi'), ('7', 'dimanche')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='', verbose_name='events/images')),
                ('titre_slug', models.SlugField(editable=False, max_length=255, null=True)),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', tinymce.models.HTMLField(verbose_name='events/description')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('ticket', models.ManyToManyField(related_name='Events', to='restaurant.Ticket')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
