# Generated by Django 2.2.8 on 2020-05-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affichmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=50, unique=True)),
                ('message', models.TextField()),
                ('cover', models.ImageField(upload_to='ouvertures')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Affiche menu',
                'verbose_name_plural': 'Affiche menus',
            },
        ),
        migrations.CreateModel(
            name='Mainevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=50, unique=True)),
                ('message', models.TextField()),
                ('cover', models.ImageField(upload_to='mainevent')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Main event',
                'verbose_name_plural': 'Main events',
            },
        ),
        migrations.CreateModel(
            name='Ouverture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=50, unique=True)),
                ('message', models.TextField()),
                ('cover', models.ImageField(upload_to='ouvertures')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ouverture',
                'verbose_name_plural': 'Ouvertures',
            },
        ),
    ]
