# Generated by Django 2.2.8 on 2020-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteConfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50, unique=True)),
                ('jours', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('tel', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footers',
            },
        ),
    ]
