# Generated by Django 3.0.6 on 2020-05-28 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteConfig', '0003_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
