# Generated by Django 3.0.6 on 2020-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteConfig', '0004_auto_20200528_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='logo_dark',
        ),
        migrations.AddField(
            model_name='logo',
            name='logo_light',
            field=models.ImageField(default='', upload_to='siteConfig'),
            preserve_default=False,
        ),
    ]
